---
params:
  SPP: "ALLSPP"
output: 
  html_document:
    keep_md: true
---

```{r include=FALSE}
if(params$SPP == "ALLSPP") commonname <- "All Bat Species"
if(params$SPP == "LABO") commonname <- "Red Bat"
if(params$SPP == "LACI") commonname <- "Hoary Bat"
if(params$SPP == "LANO") commonname <- "Silver-haired Bat"
mytitle = paste(commonname , "Museum Records")
```

---
author: "Michael Whitby"
title: `r mytitle`
---
Built with `r getRversion()`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F)

library(ggplot2)
library(gganimate)

SPP_df <- readRDS(paste0(here::here(), "/data/processed/", params$SPP, "_records.RDS"))
```


```{r graphByMonth, include=FALSE}
wmap <- suppressMessages(ggplot2::map_data('world'))

myBreaks <- function(x){
  breaks <- c(min(x),max(x))
  names(breaks) <- attr(breaks,"labels")
  breaks
}

map <- ggplot(SPP_df, aes(decimalLongitude, decimalLatitude, group = month)) +
  geom_polygon(
    aes(long, lat, group = group), fill = 'grey', colour = "black", data = wmap)+
  stat_density_2d(aes(fill = ..level..), geom="polygon", alpha = 0.25)+
  geom_point(size=0.1)+
  coord_quickmap(xlim=c(-130,-60), ylim=c(10, 60) )+
  labs(x=element_blank(), y = element_blank(), 
       title = mytitle,
       fill = element_blank())+
  # scale_fill_viridis_c(breaks = pretty_breaks(n=3),labels = c('','less', "",'more',''))+
  scale_fill_viridis_c(breaks = myBreaks, expand=expand_scale(),labels = c('Fewer Records','More Records') )+
  theme_minimal()+
  theme(legend.position="bottom")

# map

map_byMonth <- map+facet_wrap(~Fmonth)

ggsave(file=paste0(here::here(), "/output/", params$SPP, "_month.jpg"), width = 8, height = 10.5)

```

```{r showMonthlyGraph, , fig.height=10.5, fig.width=8, echo=FALSE}
map_byMonth
```

```{r graphAnimation, message=FALSE, include=FALSE, progress=F}
# anim <- map+
#   transition_time(month)+
#   labs(subtitle = 'Month: {frame_time}')+
#   ease_aes('linear')+
#   enter_fade() +
#   exit_fade()

anim <- map +
  transition_states(
    month,
    transition_length = 1,
    state_length = 2,
    wrap = T
  ) +
  labs(subtitle = 'Month: {closest_state}') +
  ease_aes('linear') +
  enter_fade() +
  exit_fade()



```
```{r showAnimation}
animate(anim, duration = 36, width=1024, height=1024)

anim_save(paste0(here::here(), "/output/", params$SPP, "_anim.gif"))
```

